### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by CosmicWebServices** [chooper100/ScratchCloudHosting#1]

**Comment by chooper100** [comment]
For now, the documentation is simply provided through the `<summary>` and `<param>` metadata in the comment tags. If you have Visual Studio (may also work with other IDEs) it will disaply this information in the autocomplete menu for each class/method/etc.

The fact is that atm this project is dead - I couldn't get it to work and since then I no longer really feel like trying to revive it :disappointed:

**Comment by CosmicWebServices** [comment]
OK
